
-- DBTYPE=MSSQL

DROP TABLE T_ORM_XML
go

DROP TABLE T_ORM_TEST
go

CREATE TABLE T_ORM_TEST (
    ID BIGINT NOT NULL IDENTITY(1,1)
    ,
    A VARCHAR(200) NULL,
    B DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    C DECIMAL(16,6) NULL,
    D DOUBLE PRECISION NULL
    , PRIMARY KEY (ID)
)
go


CREATE TABLE T_ORM_XML (
    ID BIGINT NOT NULL IDENTITY(1,1)
    ,
    ORM_TEST_ID BIGINT NULL,
    B DECIMAL(16,6) NULL
    , PRIMARY KEY (ID)
)
go



ALTER TABLE T_ORM_XML ADD FOREIGN KEY (ORM_TEST_ID) REFERENCES T_ORM_TEST(ID)
go

insert into t_orm_test(a) values('adfsd');


